port: /dev/ttyUSB0
rate: 20
joints: {
arm_shoulder_pan_joint: {id: 1, max_angle: 100, min_angle: -100, max_speed: 50},
arm_shoulder_lift_joint: {id: 2, max_angle: 100, min_angle: -100, max_speed: 50},
arm_elbow_flex_joint: {id: 3, max_angle: 100, min_angle: -100, max_speed: 50},
arm_wrist_flex_joint: {id: 4, max_angle: 100, min_angle: -100, max_speed: 50},
gripper_joint: {id: 5, max_angle: 100, min_angle: -100, max_speed: 50}
}
controllers: {
arm_controller: {type: follow_controller, joints: [arm_shoulder_pan_joint, arm_shoulder_lift_joint, arm_elbow_flex_joint, arm_wrist_flex_joint, gripper_joint],
action_name: arm_controller/follow_joint_trajectory, onboard: False }  
}
